# Generated by Django 4.2.7 on 2024-01-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
